# analysis_options.yaml

# Lint rules
linter:
  rules:
    - prefer_single_quotes
    - prefer_const_constructors
    - always_specify_types
    - avoid_print


# Dart analyzer options
analyzer:
  exclude:
    - android/**
    - ios/**
    - build/**
    - .dart_tool/**

